spring:
  application:
    name: ecommerce
  datasource:
    url: jdbc:postgresql://localhost:5432/enoca-ecommerce
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update